apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\kube\kompose.exe convert -f .\compose.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: auth
  name: auth
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: auth
